In [2]:
import numpy as np
import json
import os
import zarr

In [8]:
json_path = '/data/sternsonlab/Zhenggang/2acq/outputs/M28C_LHA_S1/stitching/c0-n5.json'
with open(json_path, 'r') as file:
    data = json.load(file)

In [9]:
type(data[0]), type(data)

(dict, list)

In [10]:
data

[{'type': 'GRAY16',
  'index': 0,
  'file': '/data/sternsonlab/Zhenggang/2acq/outputs/M28C_LHA_S1/stitching/tiles.n5/c0/c0_M28C_LHA_S1.czi_tile0',
  'position': [76.53478260869477, 39508.88695652174, -1516.0428571428574],
  'size': [1920, 1920, 1687],
  'pixelResolution': [0.23, 0.23, 0.42]},
 {'type': 'GRAY16',
  'index': 1,
  'file': '/data/sternsonlab/Zhenggang/2acq/outputs/M28C_LHA_S1/stitching/tiles.n5/c0/c0_M28C_LHA_S1.czi_tile1',
  'position': [1862.5347826086954, 39508.88695652174, -1516.0428571428574],
  'size': [1920, 1920, 1687],
  'pixelResolution': [0.23, 0.23, 0.42]},
 {'type': 'GRAY16',
  'index': 2,
  'file': '/data/sternsonlab/Zhenggang/2acq/outputs/M28C_LHA_S1/stitching/tiles.n5/c0/c0_M28C_LHA_S1.czi_tile2',
  'position': [3648.5347826086954, 39508.88695652174, -1516.0428571428574],
  'size': [1920, 1920, 1687],
  'pixelResolution': [0.23, 0.23, 0.42]},
 {'type': 'GRAY16',
  'index': 3,
  'file': '/data/sternsonlab/Zhenggang/2acq/outputs/M28C_LHA_S1/stitching/tiles.n5

In [11]:
os.path.dirname(json_path)

'/data/sternsonlab/Zhenggang/2acq/outputs/M28C_LHA_S1/stitching'

In [12]:
file0 = data[0]['file']
print(file0)
print(os.path.basename(file0))

/data/sternsonlab/Zhenggang/2acq/outputs/M28C_LHA_S1/stitching/tiles.n5/c0/c0_M28C_LHA_S1.czi_tile0
c0_M28C_LHA_S1.czi_tile0


In [13]:
parent_folder = os.path.basename(os.path.dirname(file0))
print(parent_folder)

c0


In [18]:
zarr_path = os.path.join(file0, '../../')
zarr_path = '/data/sternsonlab/Zhenggang/2acq/outputs/M28C_LHA_S1/stitching/tiles.n5'
zarr_data = zarr.convenience.open(zarr_path, mode='r')

/home/m5wei/conda/lib/python3.9/site-packages/zarr/storage.py:179: FutureWarning: The N5Store is deprecated and will be removed in a Zarr-Python version 3, see https://github.com/zarr-developers/zarr-python/issues/1274 for more information.
  return N5Store(store)


In [21]:
basepath, subpath = file0.split('.n5')

In [22]:
basepath, subpath

('/data/sternsonlab/Zhenggang/2acq/outputs/M28C_LHA_S1/stitching/tiles',
 '/c0/c0_M28C_LHA_S1.czi_tile0')

In [23]:
zarr_data = zarr.convenience.open(basepath + '.n5', mode='r')

/home/m5wei/conda/lib/python3.9/site-packages/zarr/storage.py:179: FutureWarning: The N5Store is deprecated and will be removed in a Zarr-Python version 3, see https://github.com/zarr-developers/zarr-python/issues/1274 for more information.
  return N5Store(store)


In [ ]:
zarr_data[subpath][...].shape

In [32]:
arr_1d = np.array([1, 2, 3])
# arr_3d = np.tile(arr_1d, (2, 2, 1))a
arr_3d = np.stack([arr_1d] * 4, axis=0).reshape(3, 2, 2)
print(arr_3d.shape)
arr_3d

(3, 2, 2)


array([[[1, 2],
        [3, 1]],

       [[2, 3],
        [1, 2]],

       [[3, 1],
        [2, 3]]])

In [36]:
arr_3d[:, 1, 1]

array([1, 2, 3])

In [37]:
arr_2d = np.array([[1, 2], [3, 4]])
arr_3d2 = np.stack([arr_2d] * 3, axis=0)
print(arr_3d2.shape)
arr_3d2

(3, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])